name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Node v${{ matrix.node_version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [12.x, 14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:

    - name: Setup Node.js environment.
      uses: actions/setup-node@v1.4.2

    - name: Install node-gyp globally.
      run: yarn global add node-gyp

    - name: Install modules
      run: yarn && ls

    - name: Build
      run: yarn build
